# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Case')),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('SSN', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dob', models.DateField(null=True)),
                ('sex', models.CharField(choices=[('f', 'F'), ('m', 'M')], max_length=1)),
                ('height_in_ft', models.FloatField()),
                ('weight_in_kg', models.IntegerField()),
                ('ethnicity', models.CharField(choices=[('aa', 'African American'), ('w', 'White'), ('ar', 'Arab'), ('as', 'Asian'), ('b', 'Black'), ('ro', 'Romanian'), ('la', 'Hispanic and Latino American'), ('br', 'British'), ('cu', 'Cuban'), ('ko', 'Korean'), ('en', 'English'), ('so', 'Somalian'), ('in', 'Indian'), ('ia', 'Indian American'), ('ca', 'Chinese American'), ('ch', 'Chinese'), ('ja', 'Japanese')], max_length=30)),
                ('hair_colour', models.CharField(max_length=20)),
                ('dist_mark', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ip', 'In prison'), ('ij', 'In Jail'), ('b', 'Bail'), ('ac', 'Acquitted'), ('s', 'Suspect'), ('or', 'On the run')], max_length=20)),
                ('occupation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DependsOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_f_name', models.CharField(max_length=20)),
                ('dep_l_name', models.CharField(max_length=20)),
                ('criminal_ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criminal')),
            ],
        ),
        migrations.CreateModel(
            name='Detective',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='connectedto',
            name='ssn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criminal'),
        ),
        migrations.AddField(
            model_name='case',
            name='crime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Crime'),
        ),
        migrations.AddField(
            model_name='assignedto',
            name='case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Case'),
        ),
        migrations.AddField(
            model_name='assignedto',
            name='det_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Detective'),
        ),
    ]
