# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectedto',
            old_name='ssn',
            new_name='SSN',
        ),
        migrations.RenameField(
            model_name='dependson',
            old_name='criminal_ssn',
            new_name='SSN',
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
