# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171106_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(max_length=70),
        ),
        migrations.AlterField(
            model_name='case',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='dependent',
            unique_together=set([('first_name', 'last_name')]),
        ),
    ]
